// Flat config for ESLint v9 + Expo SDK 50
const { defineConfig } = require('eslint/config');
const expo = require('eslint-config-expo/flat');

module.exports = defineConfig([
  // Global ignores so ESLint doesn't scan generated/bundled code
  {
    ignores: [
      'node_modules/**',
      'web-build/**',   // static export output
      '.expo/**',       // expo cache
      '**/_expo/**',    // nested _expo dirs in web-build
      'dist/**',
      'expo-env.d.ts',  // generated by Expo typed routes
      '**/*.d.ts',      // any generated typings
    ],
  },
  ...expo, // Expo's recommended rules
  // (Optional) restrict lint to app source
  {
    files: ['app/**/*.{js,jsx,ts,tsx}'],
  },
]);
