name: Web CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-web:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/mobile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: apps/mobile/package-lock.json

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Build web
        run: npm run build:web

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: apps/mobile/web-build
